server:
  port: 8888
spring:
  application:
    name: userInfoService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.29.203/ooad
    username: root
    password: 123456

  redis:
    host: 129.204.57.249
    password: 123456


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://47.103.29.203:6379/eureka/

# 接下来都是zuul，其它配置请放上面
zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  routes: #给服务配置路由
    userInfoService:
      path: /userInfoService/**
      url: forward:/myUser
    logService:
      path: /logService/**
      serviceId: logService
    adService:
      path: /adService/**
      serviceId: adService
    afterSaleService:
      path: /afterSaleService/**
      serviceId: afterSaleService
    paymentService:
      path: /paymentService/**
      serviceId: paymentService
    discountService:
      path: /discountService/**
      serviceId: discountService
    collectionService:
      path: /collectionService/**
      serviceId: collectionService
    commentService:
      path: /commentService/**
      serviceId: commentService
    goodsInfoService:
      path: /goodsInfoService/**
      serviceId: goodsInfoService
    topicService:
      path: /topicService/**
      serviceId: topicService
    footprintService:
      path: /footprintService/**
      serviceId: footprintService
    orderService:
      path: /orderService/**
      serviceId: orderService
    cartService:
      path: /cartService/**
      serviceId: cartService
    shareService:
      path: /shareService/**
      serviceId: shareService
    freightService:
      path: /freightService/**
      serviceId: freightService
    addressService:
      path: /addressService/**
      serviceId: addressService
    logisticsService:
      path: /logisticsService/**
      serviceId: logisticsService
    wxPaymentService:
      path: /wxPaymentService/**
      serviceId: wxPaymentService
  sensitive-headers:  #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true