server:
  port: 8888
spring:
  application:
    name: oomall-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://liznsalt:123456@localhost:9000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'routes'

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头

zuul:
  routes: #给服务配置路由
    log-service:
      path: /logs
      serviceId: oomall-log
#    ignored-services: user-service,feign-service #关闭默认路由配置
#    prefix: /oomall #给网关路由添加前缀
#  sensitive-headers:  #配置过滤敏感的请求头信息，设置为空就不会过滤
#  add-host-header: true #设置为true重定向是会添加host请求头
  whiteList: # 白名单
    - post /login
  needAdminAuthList: # 需要具有管理员的权限
    - post /goods